### ISSUE TITLE
Code Standarization: Use `createFromUri`

### ISSUE THREAD

**Issue by wilwade** [AmplicaLabs/gateway#187]
Everything should use `createFromUri` so that the key is not in the keyring in memory long term and controlled in a variable

**Comment by JoeCap08055** [comment]
The _most_ secure way would be to have the seed phrase stored in a secrets engine and retrieve it over an SSL-encrypted connection every time it's needed and generate the key just-in-time.

Another, more agnostic option would be to encrypt the seed phrase locally in memory after the first retrieval to avoid multiple fetches.

But really the question of in-memory is difficult because JS doesn't allow us control over garbage collection.
